version: '2'

services:
  graph:
    build: .
    image: graph-node7:local
    volumes:
      - ./src:/data
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev-server"]

  graph-prod:
    image: graph-node7:local
    volumes:
      - ./src:/data
    ports:
      - "3000:3000"
    command: ["npm", "start"]
